### ISSUE TITLE
Extensive testing for backend

### ISSUE THREAD

**Issue by himol7** [AmitMandliya/TeamFormationAssistant#16]
Write extensive unit tests to test the backend thoroughly.

**Comment by himol7** [comment]
@KrisshaJ can you look into the code and see what parts have already been tested?

**Comment by AmitMandliya** [comment]
@KrisshaJ @himol7 How far are we on backend testing?

**Comment by himol7** [comment]
Currently 50% of the methods have been tested already. Working on to test the rest.
