### ISSUE TITLE
Extensive testing for frontend

### ISSUE THREAD

**Issue by himol7** [AmitMandliya/TeamFormationAssistant#17]
Write extensive unit tests for front end.

**Comment by tunveyyy** [comment]
No testing for front end is currently being done

**Comment by tunveyyy** [comment]
We are planning to use [https://reactjs.org/docs/testing.html](url) library for end-to-end testing as well as for unit testing to ensure better code coverage

**Comment by AmitMandliya** [comment]
Added tests for signup js
