### ISSUE TITLE
Tests are not called by travis file

### ISSUE THREAD

**Issue by AmitMandliya** [AmitMandliya/TeamFormationAssistant#2]

**Comment by AmitMandliya** [comment]
@KrisshaJ  The task here is to create extensive test suite for backend and then call them from travis.

**Comment by tunveyyy** [comment]
The python tests are now being called from travis. We need to incorporate calling Javascript test files from travis

**Comment by AmitMandliya** [comment]
@tunveyyy I am working on it

**Comment by tunveyyy** [comment]
It is working now and I am closing this issue
