### ISSUE TITLE
Add comments for code explanation

### ISSUE THREAD

**Issue by KrisshaJ** [AmitMandliya/TeamFormationAssistant#21]
Add comments to the coding files

**Comment by AmitMandliya** [comment]
@KrisshaJ @himol7 Could you pleas add comments to the code when you do the analysis at backend

**Comment by AmitMandliya** [comment]
@KrisshaJ @himol7 Can you please make sure to close this issue once it is worked on/

**Comment by mukulv** [comment]
Required comments have been added
