### ISSUE TITLE
Improvise front end validation

### ISSUE THREAD

**Issue by tunveyyy** [AmitMandliya/TeamFormationAssistant#29]
The form gives an option to enter Experience as negative values.
Although a validation exists stating "Please enter valid experience", it would be better if we could simply not give them an option to enter a negative value

@AmitMandliya Let me know what do you think of this

**Comment by tunveyyy** [comment]
![image](https://user-images.githubusercontent.com/26518060/94806120-77496b00-03bb-11eb-87a5-86268e97fd69.png)

**Comment by mukulv** [comment]
Front end has been validated as required
