### ISSUE TITLE
Dependency issue due to presence of existing node_modules in the repository

### ISSUE THREAD

**Issue by AmitMandliya** [AmitMandliya/TeamFormationAssistant#5]
Getting error:

C:\Users\amitm\Desktop\Files\Graduation Overseas\NCSU\Courses and Materials\Semester 3\CSC510 Software Engineering\Project\TeamFormationAssistant\NodeJS>node serve.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\amitm\Desktop\Files\Graduation Overseas\NCSU\Courses and Materials\Semester 3\CSC510 Software Engineering\Project\TeamFormationAssistant\NodeJS\serve.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

**Comment by AmitMandliya** [comment]
npm install express body-parser cors mysql

**Comment by AmitMandliya** [comment]
Anybody facing these issues can delete the node_modules folder and run 'npm install express'

**Comment by tunveyyy** [comment]
We need to exclude node_modules and package-lock.json from the directory. I have raised that issue [#6](url)

**Comment by tunveyyy** [comment]
I have noticed that we would need to keep package-lock.json for travis to run. 
We need to find a work around for this

**Comment by tunveyyy** [comment]
Closing the issue as it no longer relevant due to containerized platform for running the server
