### ISSUE TITLE
Project is not well structured

### ISSUE THREAD

**Issue by tunveyyy** [AmitMandliya/TeamFormationAssistant#6]
The project does not have a proper organization of files. src folder, as well as the NodeJS folder, are present at the same level. Along with src folder, the ER diagram is also present in the same folder which is not a good way to organize the project

I would need more suggestions as to what can be improved.
@AmitMandliya @himol7 @mukulv

**Comment by himol7** [comment]
Yes, I agree with @tunveyyy . This project needs to be structured well. Moreover, README files are missing in all the folders. So there is no way to know purpose of individual folders.

**Comment by himol7** [comment]
For starters
1. Tests should be contained in a separate tests folder.
2. Images for README.md should be in a separate folder.
3. Files which are used to check the functional working of the system for eg. sqltest.py should be contained in a separate folder.

**Comment by himol7** [comment]
As of now, I am assigning this task to everyone.

**Comment by tunveyyy** [comment]
We need to ensure that package-lock.json is not included in the repository because it is something is that generated on the fly and it should be added to gitignore
