### ISSUE TITLE
Create RDS instance

### ISSUE THREAD

**Issue by AmitMandliya** [AmitMandliya/TeamFormationAssistant#9]

**Comment by AmitMandliya** [comment]
@mukulv Could you please create an instance and get the database schema set up on the same

**Comment by AmitMandliya** [comment]
@himol7 Did you receive an update from the team on setting up RDS instance?

**Comment by tunveyyy** [comment]
I do not think this is relevant right now since we have everything setup locally in a single click.

@KrisshaJ Let me know what you think

**Comment by AmitMandliya** [comment]
Closing this.
